"""Generate a deterministic transitive version lock from the active environment."""

from __future__ import annotations

import importlib.metadata as metadata
import re
import tomllib
from pathlib import Path

from packaging.requirements import Requirement
from packaging.utils import canonicalize_name


ROOT = Path(__file__).resolve().parents[1]


def main() -> int:
    config = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    direct = list(config["project"]["dependencies"])
    for requirements in config["project"].get("optional-dependencies", {}).values():
        direct.extend(requirements)
    installed = {
        canonicalize_name(dist.metadata["Name"]): dist
        for dist in metadata.distributions()
        if dist.metadata.get("Name")
    }
    pending = [canonicalize_name(Requirement(value).name) for value in direct]
    resolved: set[str] = set()
    while pending:
        name = pending.pop()
        if name in resolved:
            continue
        if name not in installed:
            raise RuntimeError(f"Required distribution is not installed: {name}")
        resolved.add(name)
        for raw in installed[name].requires or []:
            requirement = Requirement(raw)
            if requirement.marker and not requirement.marker.evaluate({"extra": ""}):
                continue
            dependency = canonicalize_name(requirement.name)
            if dependency not in resolved:
                pending.append(dependency)
    lines = [
        "# Generated by codexway/scripts/generate_lock.py",
        "# Exact direct and transitive versions from the validated environment.",
        "",
    ]
    for name in sorted(resolved):
        display_name = re.sub(r"[-_.]+", "-", installed[name].metadata["Name"])
        lines.append(f"{display_name}=={installed[name].version}")
    (ROOT / "requirements.lock").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Locked {len(resolved)} distributions")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
