name: Package entregable temporary
on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/package-entregable-temp.yml'

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Upload entregable only
        uses: actions/upload-artifact@v4
        with:
          name: Spot2_entregable_final
          path: entregable/
          if-no-files-found: error
          retention-days: 1
